/**
 * Reports.tsx — My Reports History Page
 *
 * Lists all reports generated by the currently authenticated user.
 * Design: Light editorial — matches Landing.tsx and Report.tsx exactly.
 * Palette: Off-white (#F7F5F0) bg, near-black (#1A1714) text, terracotta (#C2714F) accent
 * Typography: DM Serif Display (headings) + DM Sans (body)
 */

import { Link, useLocation } from "wouter";
import { motion } from "framer-motion";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";
import { getLoginUrl } from "@/const";

// ─── DESIGN TOKENS ────────────────────────────────────────────────────────────
const T = {
  bg: "#F7F5F0",
  bgAlt: "#F0EDE8",
  white: "#ffffff",
  border: "#E5E0D8",
  borderStrong: "#C8BEB4",
  text: "#1A1714",
  textSub: "#4A3F36",
  textMuted: "#6B5E52",
  textFaint: "#9C8E80",
  accent: "#C2714F",
  accentLight: "#FBF5F1",
  accentBorder: "#E8D5C8",
  serif: "'DM Serif Display', Georgia, serif",
  sans: "'DM Sans', system-ui, sans-serif",
};

const fadeUp = {
  hidden: { opacity: 0, y: 20 },
  visible: (delay = 0) => ({
    opacity: 1,
    y: 0,
    transition: { duration: 0.5, ease: "easeOut" as const, delay },
  }),
};

// ─── EMPTY STATE ──────────────────────────────────────────────────────────────
const EmptyState = () => (
  <motion.div
    variants={fadeUp}
    initial="hidden"
    animate="visible"
    className="flex flex-col items-center justify-center py-24 text-center"
  >
    <div
      className="w-20 h-20 rounded-full flex items-center justify-center mb-6 text-4xl"
      style={{ background: T.accentLight, border: `1px solid ${T.accentBorder}` }}
    >
      📋
    </div>
    <h2
      className="text-2xl font-bold mb-2"
      style={{ fontFamily: T.serif, color: T.text, letterSpacing: "-0.02em" }}
    >
      No reports yet
    </h2>
    <p className="text-sm mb-8 max-w-xs" style={{ color: T.textMuted }}>
      Generate your first competitor creative intelligence report to see it here.
    </p>
    <Link href="/wizard">
      <button
        className="px-6 py-3 rounded-xl text-sm font-semibold text-white transition-all hover:opacity-90 active:scale-95"
        style={{ background: T.accent, fontFamily: T.sans }}
      >
        + New Report
      </button>
    </Link>
  </motion.div>
);

// ─── REPORT CARD ──────────────────────────────────────────────────────────────
interface ReportSummary {
  id: number;
  brandName: string;
  category: string;
  isAiOnly: boolean;
  totalAdsAnalyzed: number;
  createdAt: Date;
}

const ReportCard = ({ report, index }: { report: ReportSummary; index: number }) => {
  const date = new Date(report.createdAt);
  const formattedDate = date.toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
  });
  const formattedTime = date.toLocaleTimeString("en-US", {
    hour: "numeric",
    minute: "2-digit",
  });

  return (
    <Link href={`/reports/${report.id}`}>
      <motion.div
        variants={fadeUp}
        custom={index * 0.06}
        initial="hidden"
        animate="visible"
        className="rounded-2xl border p-6 cursor-pointer group transition-shadow hover:shadow-md"
        style={{
          background: T.white,
          borderColor: T.border,
          boxShadow: "0 1px 4px rgba(26,23,20,0.06)",
        }}
      >
        <p
          className="text-xs font-semibold uppercase tracking-widest mb-2"
          style={{ color: T.accent }}
        >
          ✦ {report.category || "Competitor Analysis"}
        </p>
        <h3
          className="text-xl font-bold leading-tight mb-1 truncate"
          style={{ fontFamily: T.serif, color: T.text, letterSpacing: "-0.02em" }}
        >
          {report.brandName}
        </h3>
        <p className="text-sm italic mb-4" style={{ color: T.textMuted }}>
          Competitor Creative Analysis
        </p>
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div className="flex flex-wrap items-center gap-3">
            <span
              className="inline-flex items-center gap-1.5 text-xs font-medium px-2.5 py-1 rounded-full border"
              style={
                report.isAiOnly
                  ? { color: "#6B5E52", borderColor: T.border, background: T.bgAlt }
                  : { color: T.accent, borderColor: T.accentBorder, background: T.accentLight }
              }
            >
              {report.isAiOnly ? (
                <>
                  <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                    <circle cx="12" cy="12" r="10" />
                    <path d="M12 8v4M12 16h.01" />
                  </svg>
                  AI Analysis
                </>
              ) : (
                <>
                  <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                    <polyline points="20 6 9 17 4 12" />
                  </svg>
                  {report.totalAdsAnalyzed} real ads
                </>
              )}
            </span>
            <span className="text-xs" style={{ color: T.textFaint }}>
              {formattedDate} · {formattedTime}
            </span>
          </div>
          <span
            className="text-xs font-medium px-3 py-1.5 rounded-lg transition-colors"
            style={{ background: T.accentLight, color: T.accent, border: `1px solid ${T.accentBorder}` }}
          >
            View Report →
          </span>
        </div>
      </motion.div>
    </Link>
  );
};

// ─── SKELETON CARD ────────────────────────────────────────────────────────────
const SkeletonCard = () => (
  <div
    className="rounded-2xl border p-6 animate-pulse"
    style={{ background: T.white, borderColor: T.border }}
  >
    <div className="h-3 w-24 rounded mb-3" style={{ background: T.border }} />
    <div className="h-6 w-48 rounded mb-2" style={{ background: T.border }} />
    <div className="h-4 w-36 rounded mb-5" style={{ background: T.bgAlt }} />
    <div className="flex gap-3">
      <div className="h-6 w-20 rounded-full" style={{ background: T.bgAlt }} />
      <div className="h-6 w-32 rounded" style={{ background: T.bgAlt }} />
    </div>
  </div>
);

// ─── MAIN PAGE ────────────────────────────────────────────────────────────────
export default function Reports() {
  const { user, loading: authLoading, isAuthenticated } = useAuth();
  const [, navigate] = useLocation();

  const { data: reports, isLoading } = trpc.research.listReports.useQuery(undefined, {
    enabled: isAuthenticated,
  });

  // Redirect to login if not authenticated
  if (!authLoading && !isAuthenticated) {
    window.location.href = getLoginUrl();
    return null;
  }

  return (
    <div
      className="landing-page min-h-screen"
      style={{ background: T.bg, fontFamily: T.sans, color: T.text }}
    >
      {/* ── NAV ── */}
      <nav
        className="sticky top-0 z-50 flex items-center justify-between px-6 md:px-12 py-4"
        style={{
          background: "rgba(247,245,240,0.92)",
          backdropFilter: "blur(12px)",
          borderBottom: `1px solid ${T.border}`,
        }}
      >
        <div className="flex items-center gap-3">
          <Link href="/">
            <span
              className="text-lg font-bold cursor-pointer"
              style={{ fontFamily: T.serif }}
            >
              Scout
            </span>
          </Link>
          <span
            className="text-xs px-2 py-0.5 rounded-full font-medium"
            style={{ background: "#EDE8E1", color: T.textSub }}
          >
            Beta
          </span>
          <span
            className="hidden md:inline text-xs px-2 py-0.5 rounded-full font-medium border"
            style={{ background: T.accentLight, color: T.accent, borderColor: T.accentBorder }}
          >
            My Reports
          </span>
        </div>
        <div className="flex items-center gap-3">
          {user && (
            <span className="text-xs hidden md:block" style={{ color: T.textMuted }}>
              {user.name || user.email}
            </span>
          )}
          <Link href="/wizard">
            <button
              className="px-4 py-2 rounded-lg text-sm font-semibold text-white transition-all hover:opacity-90"
              style={{ background: T.accent }}
            >
              + New Report
            </button>
          </Link>
        </div>
      </nav>

      {/* ── HERO HEADER ── */}
      <section
        className="relative px-6 md:px-12 pt-14 pb-10 overflow-hidden"
        style={{ borderBottom: `1px solid ${T.border}` }}
      >
        {/* Dot grid */}
        <div
          className="absolute inset-0 pointer-events-none"
          style={{
            backgroundImage: `radial-gradient(circle, ${T.accent}18 1px, transparent 1px)`,
            backgroundSize: "28px 28px",
          }}
        />
        <div className="relative max-w-5xl mx-auto">
          <motion.div variants={fadeUp} custom={0} initial="hidden" animate="visible">
            <p
              className="inline-flex items-center gap-2 text-xs font-semibold uppercase tracking-widest px-3 py-1.5 rounded-full border mb-5"
              style={{ color: T.accent, borderColor: T.accentBorder, background: T.accentLight }}
            >
              ✦ Creative Intelligence
            </p>
            <h1
              className="text-4xl md:text-5xl font-bold leading-tight mb-2"
              style={{ fontFamily: T.serif, letterSpacing: "-0.02em", color: T.text }}
            >
              My Reports
            </h1>
            <p
              className="text-xl font-bold leading-tight mb-4"
              style={{ fontFamily: T.serif, fontStyle: "italic", color: T.accent }}
            >
              Your competitive intelligence archive.
            </p>
            <p className="text-sm" style={{ color: T.textMuted }}>
              {isLoading
                ? "Loading your reports…"
                : reports && reports.length > 0
                ? `${reports.length} report${reports.length !== 1 ? "s" : ""} generated`
                : "No reports yet — generate your first one below"}
            </p>
          </motion.div>
        </div>
      </section>

      {/* ── REPORTS LIST ── */}
      <div className="max-w-5xl mx-auto px-6 md:px-12 py-12">
        {authLoading || isLoading ? (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {[1, 2, 3, 4].map((i) => <SkeletonCard key={i} />)}
          </div>
        ) : !reports || reports.length === 0 ? (
          <EmptyState />
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {reports.map((report, i) => (
              <ReportCard key={report.id} report={report} index={i} />
            ))}
          </div>
        )}
      </div>

      {/* ── FOOTER ── */}
      <footer
        className="px-6 md:px-12 py-8 mt-8"
        style={{ borderTop: `1px solid ${T.border}` }}
      >
        <div className="max-w-5xl mx-auto flex items-center justify-between">
          <span className="text-sm font-bold" style={{ fontFamily: T.serif, color: T.text }}>
            Scout
          </span>
          <p className="text-xs" style={{ color: T.textFaint }}>
            © 2026 Scout · Competitive Intelligence for Creative Strategists
          </p>
        </div>
      </footer>
    </div>
  );
}
